### ISSUE TITLE
Overhaul steps

### ISSUE THREAD

**Issue by jarosm** [jarosm/KSP-BonVoyage#2]
**Phase 1:**
- [x] main window
- [x] settings window
- [x] controller window
- [x] module
- [x] base controller
- [x] rover controller
- [x] localization
- [x] Wiki
- [x] update forum thread

**Phase 2a:**
- [x] KSPWheel support when updated for 1.5.x
- [x] Kerbalism support when updated for 1.5.x - partial, only solar panels are registered
- [x] Kopernicus support when updated for 1.5.x
- [x] KSP Interstellar support when updated for 1.5.x
- [x] NF Electrical and Solar support when updated for 1.5.x
- [x] WBI support when updated for 1.5.x
- [x] USI support when updated for 1.5.x
- [x] finding a main star in a binary systems

**Phase 2b:**
- [x] catchup process
- [x] batteries
- [x] fuel cells
- [x] the rotation fix is still on the table
- [x] move a rover up/down if it's wrongly placed
- [x] Unmanned vessels must have a working connection

**Phase 3:**
- [x] someone said ship controller? :smile:
